name: Audit on Push

on:
  push:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run backend audit
        run: |
          cd backend
          npm i
          npm audit

      - name: Run frontend audit
        run: |
          cd frontend
          npm i
          npm audit